#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking_vivu
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_BOOKING")]
	public partial class dataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHUCVU(CHUCVU instance);
    partial void UpdateCHUCVU(CHUCVU instance);
    partial void DeleteCHUCVU(CHUCVU instance);
    partial void InsertTOUR(TOUR instance);
    partial void UpdateTOUR(TOUR instance);
    partial void DeleteTOUR(TOUR instance);
    partial void InsertCTHD(CTHD instance);
    partial void UpdateCTHD(CTHD instance);
    partial void DeleteCTHD(CTHD instance);
    partial void InsertHOADON(HOADON instance);
    partial void UpdateHOADON(HOADON instance);
    partial void DeleteHOADON(HOADON instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertKHACHSAN(KHACHSAN instance);
    partial void UpdateKHACHSAN(KHACHSAN instance);
    partial void DeleteKHACHSAN(KHACHSAN instance);
    partial void Insertlichtrinh(lichtrinh instance);
    partial void Updatelichtrinh(lichtrinh instance);
    partial void Deletelichtrinh(lichtrinh instance);
    partial void Insertngaytochuc(ngaytochuc instance);
    partial void Updatengaytochuc(ngaytochuc instance);
    partial void Deletengaytochuc(ngaytochuc instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertPHUONGTHUCTHANHTOAN(PHUONGTHUCTHANHTOAN instance);
    partial void UpdatePHUONGTHUCTHANHTOAN(PHUONGTHUCTHANHTOAN instance);
    partial void DeletePHUONGTHUCTHANHTOAN(PHUONGTHUCTHANHTOAN instance);
    #endregion
		
		public dataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QL_BOOKINGConnectionString2"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHUCVU> CHUCVUs
		{
			get
			{
				return this.GetTable<CHUCVU>();
			}
		}
		
		public System.Data.Linq.Table<TOUR> TOURs
		{
			get
			{
				return this.GetTable<TOUR>();
			}
		}
		
		public System.Data.Linq.Table<CTHD> CTHDs
		{
			get
			{
				return this.GetTable<CTHD>();
			}
		}
		
		public System.Data.Linq.Table<HOADON> HOADONs
		{
			get
			{
				return this.GetTable<HOADON>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<KHACHSAN> KHACHSANs
		{
			get
			{
				return this.GetTable<KHACHSAN>();
			}
		}
		
		public System.Data.Linq.Table<lichtrinh> lichtrinhs
		{
			get
			{
				return this.GetTable<lichtrinh>();
			}
		}
		
		public System.Data.Linq.Table<ngaytochuc> ngaytochucs
		{
			get
			{
				return this.GetTable<ngaytochuc>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<PHUONGTHUCTHANHTOAN> PHUONGTHUCTHANHTOANs
		{
			get
			{
				return this.GetTable<PHUONGTHUCTHANHTOAN>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.danhsachtourchuathanhtoan", IsComposable=true)]
		public IQueryable<danhsachtourchuathanhtoanResult> danhsachtourchuathanhtoan()
		{
			return this.CreateMethodCallQuery<danhsachtourchuathanhtoanResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LayThoiGianKetThucTour", IsComposable=true)]
		public System.Nullable<System.DateTime> LayThoiGianKetThucTour([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDTOUR", DbType="VarChar(10)")] string iDTOUR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayKH", DbType="Date")] System.Nullable<System.DateTime> ngayKH)
		{
			return ((System.Nullable<System.DateTime>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDTOUR, ngayKH).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.danhsachtourdathanhtoan", IsComposable=true)]
		public IQueryable<danhsachtourdathanhtoanResult> danhsachtourdathanhtoan()
		{
			return this.CreateMethodCallQuery<danhsachtourdathanhtoanResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DemSLKHBook", IsComposable=true)]
		public System.Nullable<int> DemSLKHBook([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAKH", DbType="VarChar(10)")] string mAKH)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mAKH).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fc_ngaytochuc_theothang", IsComposable=true)]
		public IQueryable<fc_ngaytochuc_theothangResult> fc_ngaytochuc_theothang([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string matour, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> thang)
		{
			return this.CreateMethodCallQuery<fc_ngaytochuc_theothangResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), matour, thang);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fc_thongke_tourdat", IsComposable=true)]
		public IQueryable<fc_thongke_tourdatResult> fc_thongke_tourdat()
		{
			return this.CreateMethodCallQuery<fc_thongke_tourdatResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fc_TinhSLKhachSanTheoDiaDiem", IsComposable=true)]
		public System.Nullable<int> fc_TinhSLKhachSanTheoDiaDiem([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ThanhPho", DbType="NVarChar(50)")] string thanhPho)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), thanhPho).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KiemTraSDTHopLe", IsComposable=true)]
		public System.Nullable<bool> KiemTraSDTHopLe([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SDT", DbType="VarChar(20)")] string sDT)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sDT).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CapNhatThongTinKH")]
		public int CapNhatThongTinKH([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaKH", DbType="VarChar(10)")] string maKH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Hoten", DbType="NVarChar(50)")] string hoten, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SDT", DbType="Char(10)")] string sDT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EMAIL", DbType="NVarChar(50)")] string eMAIL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NGSINH", DbType="Date")] System.Nullable<System.DateTime> nGSINH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GTINH", DbType="NVarChar(3)")] string gTINH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DCHI", DbType="NVarChar(50)")] string dCHI)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maKH, hoten, sDT, eMAIL, nGSINH, gTINH, dCHI);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.XEMTIEN")]
		public int XEMTIEN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDHD", DbType="VarChar(10)")] string iDHD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="THANHTIEN", DbType="Float")] ref System.Nullable<double> tHANHTIEN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDHD, tHANHTIEN);
			tHANHTIEN = ((System.Nullable<double>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThemMoiTour")]
		public int ThemMoiTour([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOURID", DbType="VarChar(10)")] string tOURID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TENTOUR", DbType="NVarChar(50)")] string tENTOUR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIADIEMTOUR", DbType="NVarChar(50)")] string dIADIEMTOUR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="THOILUONG", DbType="NVarChar(30)")] string tHOILUONG, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAKS", DbType="VarChar(10)")] string mAKS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GIATOUR", DbType="Float")] System.Nullable<double> gIATOUR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MOTA", DbType="NVarChar(255)")] string mOTA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOURID, tENTOUR, dIADIEMTOUR, tHOILUONG, mAKS, gIATOUR, mOTA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThemPhuongThucThanhToan")]
		public int ThemPhuongThucThanhToan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string idpt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tenpt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string mota)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idpt, tenpt, mota);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tinhTongDT")]
		public ISingleResult<tinhTongDTResult> tinhTongDT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> start_date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> end_date)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), start_date, end_date);
			return ((ISingleResult<tinhTongDTResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUCVU")]
	public partial class CHUCVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MACV;
		
		private string _TENCV;
		
		private EntitySet<NHANVIEN> _NHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACVChanging(string value);
    partial void OnMACVChanged();
    partial void OnTENCVChanging(string value);
    partial void OnTENCVChanged();
    #endregion
		
		public CHUCVU()
		{
			this._NHANVIENs = new EntitySet<NHANVIEN>(new Action<NHANVIEN>(this.attach_NHANVIENs), new Action<NHANVIEN>(this.detach_NHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACV", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACV
		{
			get
			{
				return this._MACV;
			}
			set
			{
				if ((this._MACV != value))
				{
					this.OnMACVChanging(value);
					this.SendPropertyChanging();
					this._MACV = value;
					this.SendPropertyChanged("MACV");
					this.OnMACVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCV", DbType="NVarChar(50)")]
		public string TENCV
		{
			get
			{
				return this._TENCV;
			}
			set
			{
				if ((this._TENCV != value))
				{
					this.OnTENCVChanging(value);
					this.SendPropertyChanging();
					this._TENCV = value;
					this.SendPropertyChanged("TENCV");
					this.OnTENCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCVU_NHANVIEN", Storage="_NHANVIENs", ThisKey="MACV", OtherKey="CHUCVU")]
		public EntitySet<NHANVIEN> NHANVIENs
		{
			get
			{
				return this._NHANVIENs;
			}
			set
			{
				this._NHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.CHUCVU1 = this;
		}
		
		private void detach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.CHUCVU1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TOUR")]
	public partial class TOUR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TOURID;
		
		private string _TENTOUR;
		
		private string _DIADIEMTOUR;
		
		private string _THOILUONG;
		
		private string _MAKS;
		
		private System.Nullable<double> _GIATOUR;
		
		private string _MOTA;
		
		private System.Nullable<int> _SoLanDat;
		
		private string _img;
		
		private EntitySet<CTHD> _CTHDs;
		
		private EntitySet<lichtrinh> _lichtrinhs;
		
		private EntitySet<ngaytochuc> _ngaytochucs;
		
		private EntityRef<KHACHSAN> _KHACHSAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTOURIDChanging(string value);
    partial void OnTOURIDChanged();
    partial void OnTENTOURChanging(string value);
    partial void OnTENTOURChanged();
    partial void OnDIADIEMTOURChanging(string value);
    partial void OnDIADIEMTOURChanged();
    partial void OnTHOILUONGChanging(string value);
    partial void OnTHOILUONGChanged();
    partial void OnMAKSChanging(string value);
    partial void OnMAKSChanged();
    partial void OnGIATOURChanging(System.Nullable<double> value);
    partial void OnGIATOURChanged();
    partial void OnMOTAChanging(string value);
    partial void OnMOTAChanged();
    partial void OnSoLanDatChanging(System.Nullable<int> value);
    partial void OnSoLanDatChanged();
    partial void OnimgChanging(string value);
    partial void OnimgChanged();
    #endregion
		
		public TOUR()
		{
			this._CTHDs = new EntitySet<CTHD>(new Action<CTHD>(this.attach_CTHDs), new Action<CTHD>(this.detach_CTHDs));
			this._lichtrinhs = new EntitySet<lichtrinh>(new Action<lichtrinh>(this.attach_lichtrinhs), new Action<lichtrinh>(this.detach_lichtrinhs));
			this._ngaytochucs = new EntitySet<ngaytochuc>(new Action<ngaytochuc>(this.attach_ngaytochucs), new Action<ngaytochuc>(this.detach_ngaytochucs));
			this._KHACHSAN = default(EntityRef<KHACHSAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOURID", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TOURID
		{
			get
			{
				return this._TOURID;
			}
			set
			{
				if ((this._TOURID != value))
				{
					this.OnTOURIDChanging(value);
					this.SendPropertyChanging();
					this._TOURID = value;
					this.SendPropertyChanged("TOURID");
					this.OnTOURIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTOUR", DbType="NVarChar(50)")]
		public string TENTOUR
		{
			get
			{
				return this._TENTOUR;
			}
			set
			{
				if ((this._TENTOUR != value))
				{
					this.OnTENTOURChanging(value);
					this.SendPropertyChanging();
					this._TENTOUR = value;
					this.SendPropertyChanged("TENTOUR");
					this.OnTENTOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIADIEMTOUR", DbType="NVarChar(50)")]
		public string DIADIEMTOUR
		{
			get
			{
				return this._DIADIEMTOUR;
			}
			set
			{
				if ((this._DIADIEMTOUR != value))
				{
					this.OnDIADIEMTOURChanging(value);
					this.SendPropertyChanging();
					this._DIADIEMTOUR = value;
					this.SendPropertyChanged("DIADIEMTOUR");
					this.OnDIADIEMTOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOILUONG", DbType="NVarChar(30)")]
		public string THOILUONG
		{
			get
			{
				return this._THOILUONG;
			}
			set
			{
				if ((this._THOILUONG != value))
				{
					this.OnTHOILUONGChanging(value);
					this.SendPropertyChanging();
					this._THOILUONG = value;
					this.SendPropertyChanged("THOILUONG");
					this.OnTHOILUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKS", DbType="VarChar(10)")]
		public string MAKS
		{
			get
			{
				return this._MAKS;
			}
			set
			{
				if ((this._MAKS != value))
				{
					if (this._KHACHSAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKSChanging(value);
					this.SendPropertyChanging();
					this._MAKS = value;
					this.SendPropertyChanged("MAKS");
					this.OnMAKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIATOUR", DbType="Float")]
		public System.Nullable<double> GIATOUR
		{
			get
			{
				return this._GIATOUR;
			}
			set
			{
				if ((this._GIATOUR != value))
				{
					this.OnGIATOURChanging(value);
					this.SendPropertyChanging();
					this._GIATOUR = value;
					this.SendPropertyChanged("GIATOUR");
					this.OnGIATOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTA", DbType="NVarChar(255)")]
		public string MOTA
		{
			get
			{
				return this._MOTA;
			}
			set
			{
				if ((this._MOTA != value))
				{
					this.OnMOTAChanging(value);
					this.SendPropertyChanging();
					this._MOTA = value;
					this.SendPropertyChanged("MOTA");
					this.OnMOTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLanDat", DbType="Int")]
		public System.Nullable<int> SoLanDat
		{
			get
			{
				return this._SoLanDat;
			}
			set
			{
				if ((this._SoLanDat != value))
				{
					this.OnSoLanDatChanging(value);
					this.SendPropertyChanging();
					this._SoLanDat = value;
					this.SendPropertyChanged("SoLanDat");
					this.OnSoLanDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this.OnimgChanging(value);
					this.SendPropertyChanging();
					this._img = value;
					this.SendPropertyChanged("img");
					this.OnimgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_CTHD", Storage="_CTHDs", ThisKey="TOURID", OtherKey="IDTOUR")]
		public EntitySet<CTHD> CTHDs
		{
			get
			{
				return this._CTHDs;
			}
			set
			{
				this._CTHDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_lichtrinh", Storage="_lichtrinhs", ThisKey="TOURID", OtherKey="matour")]
		public EntitySet<lichtrinh> lichtrinhs
		{
			get
			{
				return this._lichtrinhs;
			}
			set
			{
				this._lichtrinhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_ngaytochuc", Storage="_ngaytochucs", ThisKey="TOURID", OtherKey="matour")]
		public EntitySet<ngaytochuc> ngaytochucs
		{
			get
			{
				return this._ngaytochucs;
			}
			set
			{
				this._ngaytochucs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHSAN_TOUR", Storage="_KHACHSAN", ThisKey="MAKS", OtherKey="MAKS", IsForeignKey=true)]
		public KHACHSAN KHACHSAN
		{
			get
			{
				return this._KHACHSAN.Entity;
			}
			set
			{
				KHACHSAN previousValue = this._KHACHSAN.Entity;
				if (((previousValue != value) 
							|| (this._KHACHSAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHSAN.Entity = null;
						previousValue.TOURs.Remove(this);
					}
					this._KHACHSAN.Entity = value;
					if ((value != null))
					{
						value.TOURs.Add(this);
						this._MAKS = value.MAKS;
					}
					else
					{
						this._MAKS = default(string);
					}
					this.SendPropertyChanged("KHACHSAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTHDs(CTHD entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = this;
		}
		
		private void detach_CTHDs(CTHD entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = null;
		}
		
		private void attach_lichtrinhs(lichtrinh entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = this;
		}
		
		private void detach_lichtrinhs(lichtrinh entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = null;
		}
		
		private void attach_ngaytochucs(ngaytochuc entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = this;
		}
		
		private void detach_ngaytochucs(ngaytochuc entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTHD")]
	public partial class CTHD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHD;
		
		private System.Nullable<System.DateTime> _NGAYKH;
		
		private System.Nullable<System.DateTime> _NGAYKT;
		
		private System.Nullable<int> _SL;
		
		private string _DIADIEMDON;
		
		private string _IDTOUR;
		
		private string _NHANVIEN;
		
		private EntityRef<TOUR> _TOUR;
		
		private EntityRef<HOADON> _HOADON;
		
		private EntityRef<NHANVIEN> _NHANVIEN1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHDChanging(string value);
    partial void OnMAHDChanged();
    partial void OnNGAYKHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYKHChanged();
    partial void OnNGAYKTChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYKTChanged();
    partial void OnSLChanging(System.Nullable<int> value);
    partial void OnSLChanged();
    partial void OnDIADIEMDONChanging(string value);
    partial void OnDIADIEMDONChanged();
    partial void OnIDTOURChanging(string value);
    partial void OnIDTOURChanged();
    partial void OnNHANVIENChanging(string value);
    partial void OnNHANVIENChanged();
    #endregion
		
		public CTHD()
		{
			this._TOUR = default(EntityRef<TOUR>);
			this._HOADON = default(EntityRef<HOADON>);
			this._NHANVIEN1 = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHD", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHD
		{
			get
			{
				return this._MAHD;
			}
			set
			{
				if ((this._MAHD != value))
				{
					if (this._HOADON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAHDChanging(value);
					this.SendPropertyChanging();
					this._MAHD = value;
					this.SendPropertyChanged("MAHD");
					this.OnMAHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYKH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYKH
		{
			get
			{
				return this._NGAYKH;
			}
			set
			{
				if ((this._NGAYKH != value))
				{
					this.OnNGAYKHChanging(value);
					this.SendPropertyChanging();
					this._NGAYKH = value;
					this.SendPropertyChanged("NGAYKH");
					this.OnNGAYKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYKT", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYKT
		{
			get
			{
				return this._NGAYKT;
			}
			set
			{
				if ((this._NGAYKT != value))
				{
					this.OnNGAYKTChanging(value);
					this.SendPropertyChanging();
					this._NGAYKT = value;
					this.SendPropertyChanged("NGAYKT");
					this.OnNGAYKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL", DbType="Int")]
		public System.Nullable<int> SL
		{
			get
			{
				return this._SL;
			}
			set
			{
				if ((this._SL != value))
				{
					this.OnSLChanging(value);
					this.SendPropertyChanging();
					this._SL = value;
					this.SendPropertyChanged("SL");
					this.OnSLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIADIEMDON", DbType="NVarChar(50)")]
		public string DIADIEMDON
		{
			get
			{
				return this._DIADIEMDON;
			}
			set
			{
				if ((this._DIADIEMDON != value))
				{
					this.OnDIADIEMDONChanging(value);
					this.SendPropertyChanging();
					this._DIADIEMDON = value;
					this.SendPropertyChanged("DIADIEMDON");
					this.OnDIADIEMDONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTOUR", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDTOUR
		{
			get
			{
				return this._IDTOUR;
			}
			set
			{
				if ((this._IDTOUR != value))
				{
					if (this._TOUR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTOURChanging(value);
					this.SendPropertyChanging();
					this._IDTOUR = value;
					this.SendPropertyChanged("IDTOUR");
					this.OnIDTOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHANVIEN", DbType="VarChar(10)")]
		public string NHANVIEN
		{
			get
			{
				return this._NHANVIEN;
			}
			set
			{
				if ((this._NHANVIEN != value))
				{
					if (this._NHANVIEN1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNHANVIENChanging(value);
					this.SendPropertyChanging();
					this._NHANVIEN = value;
					this.SendPropertyChanged("NHANVIEN");
					this.OnNHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_CTHD", Storage="_TOUR", ThisKey="IDTOUR", OtherKey="TOURID", IsForeignKey=true)]
		public TOUR TOUR
		{
			get
			{
				return this._TOUR.Entity;
			}
			set
			{
				TOUR previousValue = this._TOUR.Entity;
				if (((previousValue != value) 
							|| (this._TOUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TOUR.Entity = null;
						previousValue.CTHDs.Remove(this);
					}
					this._TOUR.Entity = value;
					if ((value != null))
					{
						value.CTHDs.Add(this);
						this._IDTOUR = value.TOURID;
					}
					else
					{
						this._IDTOUR = default(string);
					}
					this.SendPropertyChanged("TOUR");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CTHD", Storage="_HOADON", ThisKey="MAHD", OtherKey="IDHD", IsForeignKey=true)]
		public HOADON HOADON
		{
			get
			{
				return this._HOADON.Entity;
			}
			set
			{
				HOADON previousValue = this._HOADON.Entity;
				if (((previousValue != value) 
							|| (this._HOADON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOADON.Entity = null;
						previousValue.CTHDs.Remove(this);
					}
					this._HOADON.Entity = value;
					if ((value != null))
					{
						value.CTHDs.Add(this);
						this._MAHD = value.IDHD;
					}
					else
					{
						this._MAHD = default(string);
					}
					this.SendPropertyChanged("HOADON");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_CTHD", Storage="_NHANVIEN1", ThisKey="NHANVIEN", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN1
		{
			get
			{
				return this._NHANVIEN1.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN1.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN1.Entity = null;
						previousValue.CTHDs.Remove(this);
					}
					this._NHANVIEN1.Entity = value;
					if ((value != null))
					{
						value.CTHDs.Add(this);
						this._NHANVIEN = value.MANV;
					}
					else
					{
						this._NHANVIEN = default(string);
					}
					this.SendPropertyChanged("NHANVIEN1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADON")]
	public partial class HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDHD;
		
		private System.Nullable<System.DateTime> _NGAYDAT;
		
		private System.Nullable<bool> _TINHTRANGTT;
		
		private System.Nullable<System.DateTime> _NGAYTT;
		
		private System.Nullable<double> _THANHTIEN;
		
		private string _MAKH;
		
		private string _IDPT;
		
		private EntitySet<CTHD> _CTHDs;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<PHUONGTHUCTHANHTOAN> _PHUONGTHUCTHANHTOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDHDChanging(string value);
    partial void OnIDHDChanged();
    partial void OnNGAYDATChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYDATChanged();
    partial void OnTINHTRANGTTChanging(System.Nullable<bool> value);
    partial void OnTINHTRANGTTChanged();
    partial void OnNGAYTTChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTTChanged();
    partial void OnTHANHTIENChanging(System.Nullable<double> value);
    partial void OnTHANHTIENChanged();
    partial void OnMAKHChanging(string value);
    partial void OnMAKHChanged();
    partial void OnIDPTChanging(string value);
    partial void OnIDPTChanged();
    #endregion
		
		public HOADON()
		{
			this._CTHDs = new EntitySet<CTHD>(new Action<CTHD>(this.attach_CTHDs), new Action<CTHD>(this.detach_CTHDs));
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._PHUONGTHUCTHANHTOAN = default(EntityRef<PHUONGTHUCTHANHTOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHD", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDHD
		{
			get
			{
				return this._IDHD;
			}
			set
			{
				if ((this._IDHD != value))
				{
					this.OnIDHDChanging(value);
					this.SendPropertyChanging();
					this._IDHD = value;
					this.SendPropertyChanged("IDHD");
					this.OnIDHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYDAT", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYDAT
		{
			get
			{
				return this._NGAYDAT;
			}
			set
			{
				if ((this._NGAYDAT != value))
				{
					this.OnNGAYDATChanging(value);
					this.SendPropertyChanging();
					this._NGAYDAT = value;
					this.SendPropertyChanged("NGAYDAT");
					this.OnNGAYDATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINHTRANGTT", DbType="Bit")]
		public System.Nullable<bool> TINHTRANGTT
		{
			get
			{
				return this._TINHTRANGTT;
			}
			set
			{
				if ((this._TINHTRANGTT != value))
				{
					this.OnTINHTRANGTTChanging(value);
					this.SendPropertyChanging();
					this._TINHTRANGTT = value;
					this.SendPropertyChanged("TINHTRANGTT");
					this.OnTINHTRANGTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTT", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYTT
		{
			get
			{
				return this._NGAYTT;
			}
			set
			{
				if ((this._NGAYTT != value))
				{
					this.OnNGAYTTChanging(value);
					this.SendPropertyChanging();
					this._NGAYTT = value;
					this.SendPropertyChanged("NGAYTT");
					this.OnNGAYTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHTIEN", DbType="Float")]
		public System.Nullable<double> THANHTIEN
		{
			get
			{
				return this._THANHTIEN;
			}
			set
			{
				if ((this._THANHTIEN != value))
				{
					this.OnTHANHTIENChanging(value);
					this.SendPropertyChanging();
					this._THANHTIEN = value;
					this.SendPropertyChanged("THANHTIEN");
					this.OnTHANHTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="VarChar(10)")]
		public string MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPT", DbType="VarChar(10)")]
		public string IDPT
		{
			get
			{
				return this._IDPT;
			}
			set
			{
				if ((this._IDPT != value))
				{
					if (this._PHUONGTHUCTHANHTOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDPTChanging(value);
					this.SendPropertyChanging();
					this._IDPT = value;
					this.SendPropertyChanged("IDPT");
					this.OnIDPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CTHD", Storage="_CTHDs", ThisKey="IDHD", OtherKey="MAHD")]
		public EntitySet<CTHD> CTHDs
		{
			get
			{
				return this._CTHDs;
			}
			set
			{
				this._CTHDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOADON", Storage="_KHACHHANG", ThisKey="MAKH", OtherKey="MAKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._MAKH = value.MAKH;
					}
					else
					{
						this._MAKH = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHUONGTHUCTHANHTOAN_HOADON", Storage="_PHUONGTHUCTHANHTOAN", ThisKey="IDPT", OtherKey="IDPT", IsForeignKey=true)]
		public PHUONGTHUCTHANHTOAN PHUONGTHUCTHANHTOAN
		{
			get
			{
				return this._PHUONGTHUCTHANHTOAN.Entity;
			}
			set
			{
				PHUONGTHUCTHANHTOAN previousValue = this._PHUONGTHUCTHANHTOAN.Entity;
				if (((previousValue != value) 
							|| (this._PHUONGTHUCTHANHTOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHUONGTHUCTHANHTOAN.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._PHUONGTHUCTHANHTOAN.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._IDPT = value.IDPT;
					}
					else
					{
						this._IDPT = default(string);
					}
					this.SendPropertyChanged("PHUONGTHUCTHANHTOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTHDs(CTHD entity)
		{
			this.SendPropertyChanging();
			entity.HOADON = this;
		}
		
		private void detach_CTHDs(CTHD entity)
		{
			this.SendPropertyChanging();
			entity.HOADON = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAKH;
		
		private string _HOTEN;
		
		private string _SDT;
		
		private string _EMAIL;
		
		private System.Nullable<System.DateTime> _NGSINH;
		
		private string _GTINH;
		
		private string _DCHI;
		
		private string _PASSWORD;
		
		private EntitySet<HOADON> _HOADONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKHChanging(string value);
    partial void OnMAKHChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnNGSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGSINHChanged();
    partial void OnGTINHChanging(string value);
    partial void OnGTINHChanged();
    partial void OnDCHIChanging(string value);
    partial void OnDCHIChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(50)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGSINH
		{
			get
			{
				return this._NGSINH;
			}
			set
			{
				if ((this._NGSINH != value))
				{
					this.OnNGSINHChanging(value);
					this.SendPropertyChanging();
					this._NGSINH = value;
					this.SendPropertyChanged("NGSINH");
					this.OnNGSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GTINH", DbType="NVarChar(3)")]
		public string GTINH
		{
			get
			{
				return this._GTINH;
			}
			set
			{
				if ((this._GTINH != value))
				{
					this.OnGTINHChanging(value);
					this.SendPropertyChanging();
					this._GTINH = value;
					this.SendPropertyChanged("GTINH");
					this.OnGTINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCHI", DbType="NVarChar(50)")]
		public string DCHI
		{
			get
			{
				return this._DCHI;
			}
			set
			{
				if ((this._DCHI != value))
				{
					this.OnDCHIChanging(value);
					this.SendPropertyChanging();
					this._DCHI = value;
					this.SendPropertyChanged("DCHI");
					this.OnDCHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOADON", Storage="_HOADONs", ThisKey="MAKH", OtherKey="MAKH")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHSAN")]
	public partial class KHACHSAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAKS;
		
		private string _TENKS;
		
		private string _DIADIEM;
		
		private string _THANHPHO;
		
		private System.Nullable<int> _SLPHONG;
		
		private EntitySet<TOUR> _TOURs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKSChanging(string value);
    partial void OnMAKSChanged();
    partial void OnTENKSChanging(string value);
    partial void OnTENKSChanged();
    partial void OnDIADIEMChanging(string value);
    partial void OnDIADIEMChanged();
    partial void OnTHANHPHOChanging(string value);
    partial void OnTHANHPHOChanged();
    partial void OnSLPHONGChanging(System.Nullable<int> value);
    partial void OnSLPHONGChanged();
    #endregion
		
		public KHACHSAN()
		{
			this._TOURs = new EntitySet<TOUR>(new Action<TOUR>(this.attach_TOURs), new Action<TOUR>(this.detach_TOURs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKS", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAKS
		{
			get
			{
				return this._MAKS;
			}
			set
			{
				if ((this._MAKS != value))
				{
					this.OnMAKSChanging(value);
					this.SendPropertyChanging();
					this._MAKS = value;
					this.SendPropertyChanged("MAKS");
					this.OnMAKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKS", DbType="NVarChar(50)")]
		public string TENKS
		{
			get
			{
				return this._TENKS;
			}
			set
			{
				if ((this._TENKS != value))
				{
					this.OnTENKSChanging(value);
					this.SendPropertyChanging();
					this._TENKS = value;
					this.SendPropertyChanged("TENKS");
					this.OnTENKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIADIEM", DbType="NVarChar(50)")]
		public string DIADIEM
		{
			get
			{
				return this._DIADIEM;
			}
			set
			{
				if ((this._DIADIEM != value))
				{
					this.OnDIADIEMChanging(value);
					this.SendPropertyChanging();
					this._DIADIEM = value;
					this.SendPropertyChanged("DIADIEM");
					this.OnDIADIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHPHO", DbType="NVarChar(50)")]
		public string THANHPHO
		{
			get
			{
				return this._THANHPHO;
			}
			set
			{
				if ((this._THANHPHO != value))
				{
					this.OnTHANHPHOChanging(value);
					this.SendPropertyChanging();
					this._THANHPHO = value;
					this.SendPropertyChanged("THANHPHO");
					this.OnTHANHPHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLPHONG", DbType="Int")]
		public System.Nullable<int> SLPHONG
		{
			get
			{
				return this._SLPHONG;
			}
			set
			{
				if ((this._SLPHONG != value))
				{
					this.OnSLPHONGChanging(value);
					this.SendPropertyChanging();
					this._SLPHONG = value;
					this.SendPropertyChanged("SLPHONG");
					this.OnSLPHONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHSAN_TOUR", Storage="_TOURs", ThisKey="MAKS", OtherKey="MAKS")]
		public EntitySet<TOUR> TOURs
		{
			get
			{
				return this._TOURs;
			}
			set
			{
				this._TOURs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TOURs(TOUR entity)
		{
			this.SendPropertyChanging();
			entity.KHACHSAN = this;
		}
		
		private void detach_TOURs(TOUR entity)
		{
			this.SendPropertyChanging();
			entity.KHACHSAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lichtrinh")]
	public partial class lichtrinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _matour;
		
		private int _ngaythu;
		
		private string _hoatdong;
		
		private EntityRef<TOUR> _TOUR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatourChanging(string value);
    partial void OnmatourChanged();
    partial void OnngaythuChanging(int value);
    partial void OnngaythuChanged();
    partial void OnhoatdongChanging(string value);
    partial void OnhoatdongChanged();
    #endregion
		
		public lichtrinh()
		{
			this._TOUR = default(EntityRef<TOUR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matour", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string matour
		{
			get
			{
				return this._matour;
			}
			set
			{
				if ((this._matour != value))
				{
					if (this._TOUR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmatourChanging(value);
					this.SendPropertyChanging();
					this._matour = value;
					this.SendPropertyChanged("matour");
					this.OnmatourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ngaythu
		{
			get
			{
				return this._ngaythu;
			}
			set
			{
				if ((this._ngaythu != value))
				{
					this.OnngaythuChanging(value);
					this.SendPropertyChanging();
					this._ngaythu = value;
					this.SendPropertyChanged("ngaythu");
					this.OnngaythuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoatdong", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string hoatdong
		{
			get
			{
				return this._hoatdong;
			}
			set
			{
				if ((this._hoatdong != value))
				{
					this.OnhoatdongChanging(value);
					this.SendPropertyChanging();
					this._hoatdong = value;
					this.SendPropertyChanged("hoatdong");
					this.OnhoatdongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_lichtrinh", Storage="_TOUR", ThisKey="matour", OtherKey="TOURID", IsForeignKey=true)]
		public TOUR TOUR
		{
			get
			{
				return this._TOUR.Entity;
			}
			set
			{
				TOUR previousValue = this._TOUR.Entity;
				if (((previousValue != value) 
							|| (this._TOUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TOUR.Entity = null;
						previousValue.lichtrinhs.Remove(this);
					}
					this._TOUR.Entity = value;
					if ((value != null))
					{
						value.lichtrinhs.Add(this);
						this._matour = value.TOURID;
					}
					else
					{
						this._matour = default(string);
					}
					this.SendPropertyChanged("TOUR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ngaytochuc")]
	public partial class ngaytochuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _matour;
		
		private System.DateTime _ngaykh;
		
		private EntityRef<TOUR> _TOUR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatourChanging(string value);
    partial void OnmatourChanged();
    partial void OnngaykhChanging(System.DateTime value);
    partial void OnngaykhChanged();
    #endregion
		
		public ngaytochuc()
		{
			this._TOUR = default(EntityRef<TOUR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matour", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string matour
		{
			get
			{
				return this._matour;
			}
			set
			{
				if ((this._matour != value))
				{
					if (this._TOUR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmatourChanging(value);
					this.SendPropertyChanging();
					this._matour = value;
					this.SendPropertyChanged("matour");
					this.OnmatourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaykh", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime ngaykh
		{
			get
			{
				return this._ngaykh;
			}
			set
			{
				if ((this._ngaykh != value))
				{
					this.OnngaykhChanging(value);
					this.SendPropertyChanging();
					this._ngaykh = value;
					this.SendPropertyChanged("ngaykh");
					this.OnngaykhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_ngaytochuc", Storage="_TOUR", ThisKey="matour", OtherKey="TOURID", IsForeignKey=true)]
		public TOUR TOUR
		{
			get
			{
				return this._TOUR.Entity;
			}
			set
			{
				TOUR previousValue = this._TOUR.Entity;
				if (((previousValue != value) 
							|| (this._TOUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TOUR.Entity = null;
						previousValue.ngaytochucs.Remove(this);
					}
					this._TOUR.Entity = value;
					if ((value != null))
					{
						value.ngaytochucs.Add(this);
						this._matour = value.TOURID;
					}
					else
					{
						this._matour = default(string);
					}
					this.SendPropertyChanged("TOUR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANV;
		
		private string _TENNV;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _GTINH;
		
		private string _SDT;
		
		private string _CHUCVU;
		
		private EntitySet<CTHD> _CTHDs;
		
		private EntityRef<CHUCVU> _CHUCVU1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnTENNVChanging(string value);
    partial void OnTENNVChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnGTINHChanging(string value);
    partial void OnGTINHChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnCHUCVUChanging(string value);
    partial void OnCHUCVUChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._CTHDs = new EntitySet<CTHD>(new Action<CTHD>(this.attach_CTHDs), new Action<CTHD>(this.detach_CTHDs));
			this._CHUCVU1 = default(EntityRef<CHUCVU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNV", DbType="NVarChar(50)")]
		public string TENNV
		{
			get
			{
				return this._TENNV;
			}
			set
			{
				if ((this._TENNV != value))
				{
					this.OnTENNVChanging(value);
					this.SendPropertyChanging();
					this._TENNV = value;
					this.SendPropertyChanged("TENNV");
					this.OnTENNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GTINH", DbType="NVarChar(3)")]
		public string GTINH
		{
			get
			{
				return this._GTINH;
			}
			set
			{
				if ((this._GTINH != value))
				{
					this.OnGTINHChanging(value);
					this.SendPropertyChanging();
					this._GTINH = value;
					this.SendPropertyChanged("GTINH");
					this.OnGTINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUCVU", DbType="VarChar(10)")]
		public string CHUCVU
		{
			get
			{
				return this._CHUCVU;
			}
			set
			{
				if ((this._CHUCVU != value))
				{
					if (this._CHUCVU1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCHUCVUChanging(value);
					this.SendPropertyChanging();
					this._CHUCVU = value;
					this.SendPropertyChanged("CHUCVU");
					this.OnCHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_CTHD", Storage="_CTHDs", ThisKey="MANV", OtherKey="NHANVIEN")]
		public EntitySet<CTHD> CTHDs
		{
			get
			{
				return this._CTHDs;
			}
			set
			{
				this._CTHDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUCVU_NHANVIEN", Storage="_CHUCVU1", ThisKey="CHUCVU", OtherKey="MACV", IsForeignKey=true)]
		public CHUCVU CHUCVU1
		{
			get
			{
				return this._CHUCVU1.Entity;
			}
			set
			{
				CHUCVU previousValue = this._CHUCVU1.Entity;
				if (((previousValue != value) 
							|| (this._CHUCVU1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHUCVU1.Entity = null;
						previousValue.NHANVIENs.Remove(this);
					}
					this._CHUCVU1.Entity = value;
					if ((value != null))
					{
						value.NHANVIENs.Add(this);
						this._CHUCVU = value.MACV;
					}
					else
					{
						this._CHUCVU = default(string);
					}
					this.SendPropertyChanged("CHUCVU1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTHDs(CTHD entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN1 = this;
		}
		
		private void detach_CTHDs(CTHD entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHUONGTHUCTHANHTOAN")]
	public partial class PHUONGTHUCTHANHTOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDPT;
		
		private string _TENPT;
		
		private string _MOTA;
		
		private EntitySet<HOADON> _HOADONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPTChanging(string value);
    partial void OnIDPTChanged();
    partial void OnTENPTChanging(string value);
    partial void OnTENPTChanged();
    partial void OnMOTAChanging(string value);
    partial void OnMOTAChanged();
    #endregion
		
		public PHUONGTHUCTHANHTOAN()
		{
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPT", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDPT
		{
			get
			{
				return this._IDPT;
			}
			set
			{
				if ((this._IDPT != value))
				{
					this.OnIDPTChanging(value);
					this.SendPropertyChanging();
					this._IDPT = value;
					this.SendPropertyChanged("IDPT");
					this.OnIDPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENPT", DbType="NVarChar(50)")]
		public string TENPT
		{
			get
			{
				return this._TENPT;
			}
			set
			{
				if ((this._TENPT != value))
				{
					this.OnTENPTChanging(value);
					this.SendPropertyChanging();
					this._TENPT = value;
					this.SendPropertyChanged("TENPT");
					this.OnTENPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTA", DbType="NVarChar(255)")]
		public string MOTA
		{
			get
			{
				return this._MOTA;
			}
			set
			{
				if ((this._MOTA != value))
				{
					this.OnMOTAChanging(value);
					this.SendPropertyChanging();
					this._MOTA = value;
					this.SendPropertyChanged("MOTA");
					this.OnMOTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHUONGTHUCTHANHTOAN_HOADON", Storage="_HOADONs", ThisKey="IDPT", OtherKey="IDPT")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.PHUONGTHUCTHANHTOAN = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.PHUONGTHUCTHANHTOAN = null;
		}
	}
	
	public partial class danhsachtourchuathanhtoanResult
	{
		
		private string _tourid;
		
		private string _tentour;
		
		private string _diadiemtour;
		
		private System.Nullable<double> _giatour;
		
		public danhsachtourchuathanhtoanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tourid", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string tourid
		{
			get
			{
				return this._tourid;
			}
			set
			{
				if ((this._tourid != value))
				{
					this._tourid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tentour", DbType="NVarChar(50)")]
		public string tentour
		{
			get
			{
				return this._tentour;
			}
			set
			{
				if ((this._tentour != value))
				{
					this._tentour = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diadiemtour", DbType="NVarChar(50)")]
		public string diadiemtour
		{
			get
			{
				return this._diadiemtour;
			}
			set
			{
				if ((this._diadiemtour != value))
				{
					this._diadiemtour = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giatour", DbType="Float")]
		public System.Nullable<double> giatour
		{
			get
			{
				return this._giatour;
			}
			set
			{
				if ((this._giatour != value))
				{
					this._giatour = value;
				}
			}
		}
	}
	
	public partial class danhsachtourdathanhtoanResult
	{
		
		private string _tourid;
		
		private string _tentour;
		
		private string _diadiemtour;
		
		private System.Nullable<double> _giatour;
		
		public danhsachtourdathanhtoanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tourid", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string tourid
		{
			get
			{
				return this._tourid;
			}
			set
			{
				if ((this._tourid != value))
				{
					this._tourid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tentour", DbType="NVarChar(50)")]
		public string tentour
		{
			get
			{
				return this._tentour;
			}
			set
			{
				if ((this._tentour != value))
				{
					this._tentour = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diadiemtour", DbType="NVarChar(50)")]
		public string diadiemtour
		{
			get
			{
				return this._diadiemtour;
			}
			set
			{
				if ((this._diadiemtour != value))
				{
					this._diadiemtour = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giatour", DbType="Float")]
		public System.Nullable<double> giatour
		{
			get
			{
				return this._giatour;
			}
			set
			{
				if ((this._giatour != value))
				{
					this._giatour = value;
				}
			}
		}
	}
	
	public partial class fc_ngaytochuc_theothangResult
	{
		
		private System.Nullable<System.DateTime> _ngaykh;
		
		public fc_ngaytochuc_theothangResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaykh", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaykh
		{
			get
			{
				return this._ngaykh;
			}
			set
			{
				if ((this._ngaykh != value))
				{
					this._ngaykh = value;
				}
			}
		}
	}
	
	public partial class fc_thongke_tourdatResult
	{
		
		private string _MATOUR;
		
		private string _TENTOUR;
		
		private System.Nullable<int> _SOLANDAT;
		
		public fc_thongke_tourdatResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATOUR", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MATOUR
		{
			get
			{
				return this._MATOUR;
			}
			set
			{
				if ((this._MATOUR != value))
				{
					this._MATOUR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTOUR", DbType="NVarChar(50)")]
		public string TENTOUR
		{
			get
			{
				return this._TENTOUR;
			}
			set
			{
				if ((this._TENTOUR != value))
				{
					this._TENTOUR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLANDAT", DbType="Int")]
		public System.Nullable<int> SOLANDAT
		{
			get
			{
				return this._SOLANDAT;
			}
			set
			{
				if ((this._SOLANDAT != value))
				{
					this._SOLANDAT = value;
				}
			}
		}
	}
	
	public partial class tinhTongDTResult
	{
		
		private System.Nullable<double> _tong;
		
		public tinhTongDTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tong", DbType="Float")]
		public System.Nullable<double> tong
		{
			get
			{
				return this._tong;
			}
			set
			{
				if ((this._tong != value))
				{
					this._tong = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
