<?xml version="1.0" encoding="utf-8"?><Database Name="QL_KHACHSAN" Class="dataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-U43BCKE\SQLEXPRESS;Initial Catalog=QL_KHACHSAN;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QL_KHACHSANConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BOPHAN" Member="BOPHANs">
    <Type Name="BOPHAN">
      <Column Name="MABP" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENBP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="BOPHAN_NHANVIEN" Member="NHANVIENs" ThisKey="MABP" OtherKey="MABP" Type="NHANVIEN" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="TENDN" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MK" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="NHANVIEN_TAIKHOAN" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETKH" Member="CHITIETKHs">
    <Type Name="CHITIETKH">
      <Column Name="MAHD" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SOCCCD" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGSINH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="QUANHE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="HOADON_CHITIETKH" Member="HOADON" ThisKey="MAHD" OtherKey="MAHD" Type="HOADON" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTDV" Member="CTDVs">
    <Type Name="CTDV">
      <Column Name="MADV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAHD" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DICHVU_CTDV" Member="DICHVU" ThisKey="MADV" OtherKey="MADV" Type="DICHVU" IsForeignKey="true" />
      <Association Name="HOADON_CTDV" Member="HOADON" ThisKey="MAHD" OtherKey="MAHD" Type="HOADON" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTHD" Member="CTHDs">
    <Type Name="CTHD">
      <Column Name="MAHD" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAPH" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYNHAN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYTRA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TINHTRANG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="HOADON_CTHD" Member="HOADON" ThisKey="MAHD" OtherKey="MAHD" Type="HOADON" IsForeignKey="true" />
      <Association Name="PHONG_CTHD" Member="PHONG" ThisKey="MAPH" OtherKey="MAPH" Type="PHONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DICHVU" Member="DICHVUs">
    <Type Name="DICHVU">
      <Column Name="MADV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENDV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIADV" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="DICHVU_CTDV" Member="CTDVs" ThisKey="MADV" OtherKey="MADV" Type="CTDV" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MAHD" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKH" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MAPT" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MANV" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MAKS" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NGAYDAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYTHANHTOAN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TINHTRANG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DATRA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="HOADON_CHITIETKH" Member="CHITIETKHs" ThisKey="MAHD" OtherKey="MAHD" Type="CHITIETKH" />
      <Association Name="HOADON_CTDV" Member="CTDVs" ThisKey="MAHD" OtherKey="MAHD" Type="CTDV" />
      <Association Name="HOADON_CTHD" Member="CTHDs" ThisKey="MAHD" OtherKey="MAHD" Type="CTHD" />
      <Association Name="KHACHHANG_HOADON" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="KHACHSAN_HOADON" Member="KHACHSAN" ThisKey="MAKS" OtherKey="MAKS" Type="KHACHSAN" IsForeignKey="true" />
      <Association Name="NHANVIEN_HOADON" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="PHUONGTHUCTHANHTOAN_HOADON" Member="PHUONGTHUCTHANHTOAN" ThisKey="MAPT" OtherKey="MAPT" Type="PHUONGTHUCTHANHTOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MAKH" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGSINH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GTINH" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="QUOCTICH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SOCCCD" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="KHACHHANG_HOADON" Member="HOADONs" ThisKey="MAKH" OtherKey="MAKH" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHSAN" Member="KHACHSANs">
    <Type Name="KHACHSAN">
      <Column Name="MAKS" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KHACHSAN_HOADON" Member="HOADONs" ThisKey="MAKS" OtherKey="MAKS" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIPHONG" Member="LOAIPHONGs">
    <Type Name="LOAIPHONG">
      <Column Name="MALOAI" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="LOAIPHONG_PHONG" Member="PHONGs" ThisKey="MALOAI" OtherKey="MALOAI" Type="PHONG" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MANV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MABP" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TENNV" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="SODT" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="Char(12)" CanBeNull="true" />
      <Association Name="NHANVIEN_TAIKHOAN" Member="TAIKHOANs" ThisKey="MANV" OtherKey="MANV" Type="TAIKHOAN" />
      <Association Name="NHANVIEN_HOADON" Member="HOADONs" ThisKey="MANV" OtherKey="MANV" Type="HOADON" />
      <Association Name="BOPHAN_NHANVIEN" Member="BOPHAN" ThisKey="MABP" OtherKey="MABP" Type="BOPHAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHONG" Member="PHONGs">
    <Type Name="PHONG">
      <Column Name="MAPH" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALOAI" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TENPH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TINHTRANG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SLCHUA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOGIUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIAPHONG" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="PHONG_CTHD" Member="CTHDs" ThisKey="MAPH" OtherKey="MAPH" Type="CTHD" />
      <Association Name="LOAIPHONG_PHONG" Member="LOAIPHONG" ThisKey="MALOAI" OtherKey="MALOAI" Type="LOAIPHONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHUONGTHUCTHANHTOAN" Member="PHUONGTHUCTHANHTOANs">
    <Type Name="PHUONGTHUCTHANHTOAN">
      <Column Name="MAPT" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENPT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="PHUONGTHUCTHANHTOAN_HOADON" Member="HOADONs" ThisKey="MAPT" OtherKey="MAPT" Type="HOADON" />
    </Type>
  </Table>
</Database>