--nguyen van thanh
CREATE TABLE KHOA
(
	MAKHOA CHAR(10) NOT NULL PRIMARY KEY,
	TENKHOA NVARCHAR(50)
)

CREATE TABLE SINHVIEN(
	MASV CHAR(10) NOT NULL PRIMARY KEY,
	HOTEN NVARCHAR(50),
	NGAYSINH DATETIME,
	GTINH NVARCHAR(3),
	DCHI NVARCHAR(50),
	MALOP CHAR(10)
)

CREATE TABLE LOP(
	MALOP CHAR(10) NOT NULL PRIMARY KEY,
	TENLOP NVARCHAR(50),
	SISO INT,
	LOPTRUONG CHAR(10),
	MAKH CHAR(10)
	FOREIGN KEY(LOPTRUONG) REFERENCES SINHVIEN(MASV),
	FOREIGN KEY(MAKH) REFERENCES KHOA(MAKHOA)
)

ALTER TABLE SINHVIEN
	ADD FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)


CREATE TABLE GIANGVIEN(
	MAGV CHAR(10) NOT NULL PRIMARY KEY,
	TENGV NVARCHAR(50),
	MAKH CHAR(10),
	FOREIGN KEY (MAKH) REFERENCES KHOA(MAKHOA)	
)

CREATE TABLE MONHOC(
	MAMH CHAR(10) NOT NULL PRIMARY KEY,
	TENMH NVARCHAR(50),
	SOTC INT,
)

CREATE TABLE DIEM(
	MASV CHAR(10) NOT NULL,
	MAMH CHAR(10) NOT NULL,
	LANTHI INT NOT NULL,
	DIEMTHI FLOAT
	PRIMARY KEY (MASV, MAMH, LANTHI)
	FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
	FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
)

CREATE TABLE GIANGDAY(
	MAGV CHAR(10) NOT NULL,
	MAMH CHAR(10) NOT NULL,
	NAMHOC CHAR(10),
	HOCKY INT
	PRIMARY KEY (MAGV, MAMH)
	FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
	FOREIGN KEY (MAGV) REFERENCES GIANGVIEN(MAGV)
)

CREATE TABLE THANNHAN(
	MATN CHAR(10) NOT NULL PRIMARY KEY,
	HOTEN NVARCHAR(50),
	GIOITINH NVARCHAR(3)
)

CREATE TABLE QUANHE(
	MATN CHAR(10),
	MASV CHAR(10),
	QUANHE NVARCHAR(30)
	FOREIGN KEY (MATN) REFERENCES THANNHAN(MATN),
	FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV)
)