-- nguyen van thanh

--Cau 2
UPDATE SINHVIEN
SET DCHI = N'Cần Thơ'
WHERE MASV = 'SV002'

--CAU 4
SELECT MASV, HOTEN
FROM SINHVIEN
WHERE DCHI = N'Vũng Tàu'

--CAU 5
SELECT SOTC
FROM MONHOC
WHERE TENMH = N'Toán rời rạc'

--CAU 6
SELECT TENLOP
FROM LOP, KHOA
WHERE LOP.MAKH = KHOA.MAKHOA
AND TENKHOA = N'Công nghệ thông tin'

--CAU 7
SELECT MASV, HOTEN
FROM SINHVIEN
WHERE HOTEN LIKE N'Nguyễn%'

--CAU 8
SELECT HOTEN, NGAYSINH, DCHI
FROM SINHVIEN
WHERE GTINH = N'Nam' AND MALOP = '10DHTH1'

--CAU 9
SELECT TENMH
FROM MONHOC
WHERE SOTC = 1 OR SOTC = 2

-- CAU 10
SELECT HOTEN, DCHI
FROM SINHVIEN, KHOA, LOP
WHERE LOP.MAKH = KHOA.MAKHOA AND SINHVIEN.MALOP = LOP.MALOP
AND TENKHOA = N'Công nghệ thông tin' AND GTINH = N'Nữ'

-- CAU 11
SELECT *
FROM SINHVIEN
WHERE GTINH = N'Nữ' AND ( DCHI = N'TPHCM' OR DCHI = N'Vũng Tàu' )

--CAU 12
SELECT *
FROM SINHVIEN, DIEM
WHERE SINHVIEN.MASV = DIEM.MASV
AND DIEMTHI BETWEEN 6 AND 8

--CAU 13
SELECT SINHVIEN.*
FROM SINHVIEN, LOP, KHOA, DIEM
WHERE SINHVIEN.MALOP = LOP.MALOP AND LOP.MAKH = KHOA.MAKHOA AND SINHVIEN.MASV = DIEM.MASV
AND TENKHOA = N'Công nghệ thông tin' AND  MAMH = 'CSDL' AND DIEMTHI > 5

-- CAU 14
SELECT KHOA.TENKHOA, COUNT(*) AS SLLOP
FROM KHOA, LOP
WHERE KHOA.MAKHOA = LOP.MAKH
GROUP BY LOP.MAKH, KHOA.TENKHOA

-- CAU 15
SELECT TENLOP, COUNT(*) AS SLSV
FROM SINHVIEN, LOP
WHERE SINHVIEN.MALOP = LOP.MALOP
GROUP BY SINHVIEN.MALOP, LOP.TENLOP

-- CAU 16
SELECT TENKHOA, COUNT(*) AS SLSV
FROM KHOA, LOP, SINHVIEN
WHERE KHOA.MAKHOA = LOP.MAKH
AND SINHVIEN.MALOP = LOP.MALOP
GROUP BY KHOA.MAKHOA, KHOA.TENKHOA
ORDER BY COUNT(*) ASC

-- CAU 17
SELECT DIEM.MASV, HOTEN, AVG(DIEMTHI)AS DTB
FROM SINHVIEN , DIEM
WHERE SINHVIEN.MASV = DIEM.MASV
GROUP BY DIEM.MASV, SINHVIEN.HOTEN

-- CAU 18
SELECT DIEM.MASV, COUNT(*) AS SOMON
FROM SINHVIEN, DIEM
WHERE SINHVIEN.MASV = DIEM.MASV
GROUP BY DIEM.MASV